// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // 지문·얼굴 로그인(패스키) 활성화 — supabase-js 실험 기능이라 타입에 아직 없어 캐스팅으로 넘긴다.
    // ⚠️ 이 파일이 자동 생성으로 덮이면 이 줄이 사라지고 패스키가 조용히 안 된다. 그때 다시 넣을 것.
    ...({ experimental: { passkey: true } } as object),
  }
});